@startuml Componentes
left to right direction
skinparam componentStyle uml2
skinparam nodesep 60
skinparam ranksep 80

title Diagrama de Componentes Apache CloudStack

component "Servidor de Administración" as MS

component "CloudStack API" as API
component "Plugins de Extensión" as PLUG

component "Agentes" as AG

package "Máquinas Virtuales del Sistema" {
    component "Router Virtual (VR)" as VR
    component "Almacenamiento Secundario (SSVM)" as SSVM
    component "Console Proxy VM" as CPVM
}

interface "ApiServer" as iAPI
interface "HypervisorResource" as iAG
interface "VirtualMachine\nManager" as iSVM
interface "PluggableService" as iPLUG


API -- iAPI
iAPI )-- MS

PLUG -- iPLUG
iPLUG )-- MS

MS --( iAG
iAG -- AG

MS --( iSVM
iSVM -- VR
iSVM -- SSVM
iSVM -- CPVM

@enduml
